* Rich-Media Assignments

What is a rich-media assignment? These can take a number of forms, including:

- Videos
- Posters
- Podcasts
- Ebooks
- Photo Journals

These forms draw on rhetorical modes and conventions that are different from traditional writing assignments. However, this doesn't mean that they are fundamentally less rigorous. The fundamental skills required for writing a strong paper, including research, citation, coherence, and organization, are still required for a successful. rich-media assignment.

* Advantages of Rich-Media Assignments

1. Breaks students out of rhetorical ruts. How often have you read this opening? "Throughout history, humanity has always done <thing related to topic>..."
2. Students often have baggage and bad habits that they have picked up from past writing assignments. Students don't know that they can record a podcast the night before an assignment is due, and that uncertainty can work to your advantage as an instructor.
3. Rich-media assignments often feel less artificial and more "real" to students. Students are often consumers of rich media and are excited to create their own.
4. Unlike papers, which are almost always only read by the instructor, students can often imagine peers or the public consuming their thoughts as articulated in rich media.
5. Rich-media assignments can serve to preface, supplement, or follow up more traditional writing assignments. Students are often excited to write up their thoughts after creating rich media, since they often put considerable effort into a rich media assignment.
6. It's often obvious to students when a rich media assignment they've created isn't working, while many students have become inuredd or accustomed to low-quality papers.

* Scaffolding Rich-Media Assignments

While they are rewarding, rich-media assignments often require a great deal of work on the part of instructor and student. Typically, rich media assignments require two kinds of prepatory work:
 
1. Conceptual scaffolding in the form of sustained group work, classroom exercises, and low-stakes writing assignments.
2. Technical preparation in the form of in-class workshops, consultations, and "dry runs."

** Conceptual Scaffolding

Rich-media assignments tend to be motivating for students, and so they can often make for a strong capstone or final assignment. Earlier work can be structured as preparation for a final rich-media project. For example, if a final project was conceived as a video on the evolution of a chosen genus, the instructor could assign a midterm literature review, a script for the video with correct citations, and two blog posts on planning for the creation of the video.

** Technical Scaffolding

It's important to realize that technical considerations in facilitating rich-media assignments can take up class time, often in unanticipated ways. When scheduling in-class exercises aroudn rich media, build in more time than you anticipate needing. You may want to create collections of resources or a running FAQ for your students on your course site. 

It's also important to incorporate a "dry run" into your curriculum—that is, a low-stakes assignment that forces students to do a very basic version of the final assignment, ideally well before the actual project is due. For example, if the rich-media assignment is a podcast, students should be asked to create and upload one minute of audio. This will help you and your students to work out technical kinks before starting serious work on the assignment you will be grading.

* Embedding Rich Media

WordPress (and Qwriting) allow for the embedding of rich media into posts and pages. This can be a good way for students to turn in their rich-media assignments. Photo journals can be created this way, and videos and sound recordings can be embedded within posts after being uploaded to platforms such as [[https://www.youtube.com/][YouTube]], [[https://vimeo.com/][Vimeo]], or [[https://soundcloud.com/search/sounds][SoundCloud]].

** How to embed media in WordPress

1. Find the page dedicated to the piece of media you would like to embed. Supported platforms include YouTube, Vimeo, SoundCloud, Twitter, Spotify, and Facebook. Visit [[https://codex.wordpress.org/Embeds][this page]] for a full list of supported platforms (scroll to the bottom).
2. Copy the full URL for your selected platform. That's the text starting with "http" at the top of your web browser. 
3. In WordPress, open the post or page you'd like the media to appear in. Make sure the tab on the top right of the edit pane is set to "visual" and not "text." Start a new blank line in the edit pane and paste the full URL onto that line. You should see the media embedded in the edit pane, and the change should be reflected in the preview view of the post.

You can use the below URL to test the embedding functionality:

https://soundcloud.com/iamalik/zadie-smith-lecture-why-write-creativity-and-refusal/sets


rubrics for non-traditional assignments

privacy and ethical considerations of public-facing classroom



* portfolios

* Resources
[[https://ltlatnd.wordpress.com/2012/11/05/how-to-design-a-digital-media-project/][How to design a digital media assignment]]

